Repository uni-helper/vite-plugin-uni-pages, pull requests merged in 2024-07, with the labels that each got.

#175 fix(core): fix the same page path
  packages/core/src/context.ts
  packages/playground/src/pages-sub-pages/sub-main/pages/about/index.nvue
  packages/playground/src/pages/index.nvue
  test/files.spec.ts
  test/generate.spec.ts
Labels: size/S

#177 fix: import groupBy from lodash.groupBy instead of lodash-unified
  packages/core/package.json
  packages/core/src/utils.ts
  pnpm-lock.yaml
Labels: size/M

#179 fix(core): fix the module exports
  packages/core/src/context.ts
Labels: size/XS
