Repository uni-helper/vite-plugin-uni-pages, pull requests merged in 2025-09, with the labels that each got.

#235 fix(core): 修复依赖ESM-ONLY版本导致CJS项目报错问题
  packages/core/package.json
  pnpm-lock.yaml
Labels: size/XS

#234 fix: #232 auto generate tabbar list item
  packages/core/src/context.ts
  packages/core/src/page.ts
  packages/core/src/types.ts
  packages/playground/src/pages/define-page/object.vue
  test/generate.spec.ts
Labels: size/L

#237 fix #231 filter no named imports
  packages/core/src/page.ts
Labels: size/S

#240 fix: #238 hot reload error
  packages/core/src/page.ts
Labels: size/M

#244 fix: #242 解决无配置 tabbar 时，依然生成空数组的 tabbar 的bug
  packages/core/src/context.ts
Labels: size/S

#249 pages.json 内使用条件编译区分不同环境
  .vscode/launch.json
  packages/core/src/context.ts
  packages/core/src/files.ts
  packages/core/src/index.ts
  packages/core/src/utils.ts
Labels: size/L
