Repository uni-helper/vite-plugin-uni-pages, pull requests merged in 2025-08, with the labels that each got.

#212 feat: 类型兼容自定义tabBar的情况
  packages/core/src/config/types/tabBar.ts
Labels: size/XS

#214 chore: update dependencies to fix high-version Node.js compatibility
  packages/core/package.json
  pnpm-lock.yaml
Labels: size/XS

#219 feat: 保留route中的注释
  package.json
  packages/core/package.json
  packages/core/src/context.ts
  packages/core/src/customBlock.ts
  packages/core/src/files.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
  packages/playground/src/pages/test-jsonc-with-comment.vue
  pnpm-lock.yaml
  test/files.spec.ts
  test/generate.spec.ts
  test/parser.spec.ts
Labels: size/L

#220 feat: routeBlockLang 新增 'jsonc' 类型和文档说明
  README.md
  packages/core/README.md
  packages/core/src/types.ts
Labels: size/XS

#229 fix(types): change `definePage` to global scope
  packages/core/client.d.ts
Labels: size/XS

#230 perf: break loop wihen found the first definePage
  packages/core/src/page.ts
Labels: size/S
